title: Open Build Service
site: https://openbuildservice.org
highlighter: rouge
permalink: /:year/:month/:day/:title/
markdown: kramdown
include: [ '_redirects' ]
# Do not publish posts with a future date
future: false

plugins:
  - jemoji
