title: Open Build Service
description: |
  Create and Distribute Software Packages for all Major Linux
  Distributions with all the Tools to Work Together!
highlighter: rouge
url: https://openbuildservice.org
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
include: [ '_redirects' ]
# Number of posts per page
paginate: 20
# First page is blog/, second is blog/page2/, and so on...
paginate_path: "/blog/page:num/"

plugins:
  - jemoji
  - jekyll-paginate
